name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [A]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Build flavor ${{ matrix.flavor }}
        run: python build.py ${{ matrix.flavor }}
      
      - name: Create artifact directory
        run: |
          mkdir -p artifacts
          cp build.py artifacts/
          echo "Flavor: ${{ matrix.flavor }}" > artifacts/flavor.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-flavor-${{ matrix.flavor }}
          path: artifacts/
